### PR TITLE
Huge refactor 

### PR DESCRIPTION
**Pull request by fonix232**
UI implementations for login and main chat view, proper MVVM implementation, etc.

### CODE REVIEW

**Comment by thang2410199** [comment]
I agree with most of the changes, there are a two things I don't.

The **NavigatorService** come with MVVM Light has limitations that I would not recommend using. It has limited configuration, couldn't handle more than 1 frame out of the box (so you cant have fully customized navigation model). The current approach prioritize customization and controlling. You can extend it to support navigating with multiple frames (e.g for multi-level setting pane / youtube-style detachable players / notification in app).

Puting styling into xaml Page is not intuitive, it should be centralize in a single style dictionary for better code reading and tracing. Plus it makes xaml page lean.

**Comment by kfechter** [comment]
ok. i'll hold off merging this for now.

**Comment by fonix232** [comment]
Styling can go into a central style ResourceDictionary, I agree on that
(however there's only one style here that we're talking about).

However I do not agree with the NavigationService you implemented. Sure,
the stock MVVMLight one is VERY limited (that's why I expanded it with some
of my own additions, see Services/NavigationService.cs), however your
additional hooks into Page navigation events are totally unnecessary. Those
can be solved by calling specific methods within the ViewModel (which again
can be accessed either as a property (this.DataContext as xViewModel) or
through App.Current.Locator.x), which would be the preferred way of
handling things. Interfacing the ViewModel and making an arbitrary class
for pages and a mandatory implementation for stuff within the ViewModel is
simply bad design.

Your approach would be viable if navigation was done by ViewModel
reference, not Page reference (like on Android, where you have Activities
initializing the layouts). But unfortunately it is not done that way.

A better solution would be making an abstract class based on ViewModelBase
and INavigable, and using that as base class for other ViewModels. That way
the interface is implemented, but adding the code is not mandatory. If you
wish, I can add that, and the re-implementation of your NavigationService,
to my changes tomorrow.

Also, most of my modifications (making all the helpers, and "core" stuff
into separate services) should be merged. Unfortunately I took a big step
with my refactor, which means a lot of things changed, mostly for the
better. I understand that this is a fresh project, but naming conventions
(Views instead of View, ViewModels instead of ViewModel, etc.), code
placement (controls, user controls go into Controls, only make helpers for
things that you can't solve with a singular service, etc.) should be
followed.

For the UI, this is just an initial wrap-up. My design for now is
desktop-oriented, but with VisualStates, we can easily move the CommandBar
from top to the bottom (in which case we further shrink the usable screen
space). My main design source was the Android Hangouts app, so I was
following mainly Android design guidelines (which means command bar with
title and hamburger on top, etc.). However I'm open to suggestions.

I'll push some further changes tomorrow to fix most of these issues.

**Comment by thang2410199** [comment]
In MVVM, things should be separated between View and ViewModel, they should function without knowing each other. So I would want to handle navigation events on ViewModel rather than create new method for each ViewModel. The implementation is **not** mandatory, you can choose to opt-out of the INavigable interface or leave implementation blank.

Can you explain more about this by a sample case, I am still not see it clear :(
<q>Your approach would be viable if navigation was done by ViewModel
reference, not Page reference</q>

**Comment by fonix232** [comment]
The NavigationService is practically a copypaste of the MVVMLight Win81 one, with the addition of frame switching on demand.

Indeed they should be separate, but the way UWP is built up, you cannot fully separate them - there are times when calling into the ViewModel is needed. Luckily we have event binding, so instead of commands (for interfaces that do not support it), a Click, Tap, etc. event can be implemented in the VM, and you can simply bind to it. Unfortunately the base Page class does not expose the NavigatedTo, etc. navigation events :\ otherwise it'd be a single line to bind to the VM implementation.

**Comment by fonix232** [comment]
As for the "Your approach would be viable if navigation was done by ViewModel
reference, not Page reference".

Basically I mean that when you navigate around, you do that by referencing the Page type and passing one or more arguments (which ends up in the ViewModel 99% of the times). If we were to navigate by referencing ViewModels (and the framework loading the assigned Page), this Navigation system you developed would work perfectly. But all you did was to hide the code behind in a parent class.

**Comment by thang2410199** [comment]
The Navigation system you are using has basically the same principles (hold a Frame, navigate using runtime defined keys, store key/type in dictionary). So what would be the problem here ? (I mean in my Navigation system).

 I am hiding the implementation in a parent class (BindablePage in this case), saving us from writing navigation event in Views, handle them in ViewModels.

Without BindablePage, we will have to write handler for navigation events in Views, than call specific method(s) in ViewModels from Views. In your current commit, you don't show any way to handle those events (navigation) in VM, making INavigable useless.

My suggestion is keep using BindablePage, as it enable leaner code and is adaptive to changes.

**Comment by fonix232** [comment]
My commit does not use navigation events, and I do not see any further case where it would be needed.

I did not say that my navigation service is perfect, or follows the way I defined - I actually pointed out that this way, our current way, is not viable for what you're trying to do.

And you hiding the code in the parent class does not make it a better MVVM pattern - it just makes it hidden, obscure, and unnecessarily mandatory in cases. BindablePage adds unnecessary clunk to the existing code (my code works just fine, mind you!), and the INavigable interface does so too.

Instead of adding more clunk to parent classes, I'd suggest making an implementation of the Page class that actually has the NavigatedTo, NavigatedFrom, NavigatingTo, NavigatingFrom, etc. navigation events exposed, not just an override.

**Comment by thang2410199** [comment]
Handling the navigation events is much needed. E.g: in the first page user navigate to, check the login state....In the commit, there is no sign of handling them in VM.

The current way is proof to be viable in my projects, there is no limitation or extra work required with it so far. And they (my apps) have difference navigation requirements FYI. (menu-detail / youtube like / facebook like ... )

I agree that expose the Page's events is a improvement :+1:

**Comment by fonix232** [comment]
As of now, it is NOT needed. I handle the loggedin/loggedout state in App.xaml.cs, however in the future it could be handled by a VisualState - so all is on one core page.

I will however try to make a Page implementation that has these events exposed.

**Comment by kfechter** [comment]
I merged it. It can be played with later.

**Pull request merged**
